In [ ]:
import numpy as np

In [ ]:
np.array(range(4))

array([0, 1, 2, 3])

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
x = np.arange(1, 4, 1)

In [ ]:
x

array([1, 2, 3])

In [ ]:
x.shape

(3,)

In [ ]:
x[1]

1.5

In [ ]:
np.array([range(4), range(4)])

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
X = np.array([range(4), range(4),range(4)])

In [ ]:
X

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
X.shape

(3, 4)

In [ ]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y=np.array([[1,2,3],[4,5,6]])

In [ ]:
y.shape

(2, 3)

In [ ]:
y.transpose

<function ndarray.transpose>

In [ ]:
y.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
y.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y[0]

array([1, 2, 3])

In [ ]:
y[1]

array([4, 5, 6])

In [ ]:
y[1]-y[0]

array([3, 3, 3])

Euclidean Distance

It’s the straight line distance between the two points defined by your vectors (the “tips” or “heads” of those vectors).

Euclidean distance is also called L2 norm, because it’s the length of the vector difference between two vectors. The “L” in L2 stands for length. The “2” in L2 represents the exponent (squaring) of the dimensions of the difference vector before these values ares summed (and before the square root of the sum).

Euclidean distance is also called the RSS distance, which stands for the root sum square distance or difference, which means:

In [ ]:
#euclidean_distance = np.sqrt(((vector1 - vector2) ** 2).sum())
import numpy as np
euclidean_distance = np.sqrt(((y[1] - y[0]) ** 2).sum())

In [ ]:
euclidean_distance


5.196152422706632

Wired Magazine and Town and Country. And we want to be able to query that set of articles while researching something to find some articles about a particular topic. The query string has both the words “hacking” and “computers” in it. Our query string word vector is [1, 1] for the words “hack” and “computer” because our query tokenized and stemmed the words that way

Query=hacking computers

![image.png](attachment:image.png)

Cosine Distance

Cosine distance is the inverse of the cosine similarity (cosine_distance = 1 - cosine_similarity)

the angle between the TF vector for this query string and the vector for Wired Magazine articles would be much smaller than the angle between the query and the Town and Country articles. This is what we want. Because a query about “hacking computers” should give us Wired Magazine articles and not articles about recreational activities like horse riding (“hacking”), duck hunting, dinner parties, and rustic interior design.

Two normalized vectors, vectors whose values have all been divided by the length of the vector

In [ ]:
import numpy as np
vector_query = np.array([1, 1])
vector_tc = np.array([1, 0])
vector_wired = np.array([5, 6])
normalized_query = vector_query / np.linalg.norm(vector_query)
normalized_tc = vector_tc / np.linalg.norm(vector_tc)
normalized_wired = vector_wired / np.linalg.norm(vector_wired)


In [ ]:
normalized_query

array([0.70710678, 0.70710678])

In [ ]:
normalized_tc

array([1., 0.])

In [ ]:
normalized_wired

array([0.6401844 , 0.76822128])

Cosine Simmilarity

The cosine similarity between our query TF vector and these other two TF vectors (cosine of the angle between them) is

In [ ]:
np.dot(normalized_query, normalized_tc)  # cosine similarity



0.7071067811865475

In [ ]:
np.dot(normalized_query, normalized_wired)  # cosine similarity

0.9958932064677037

The cosine distance between our query and these two TF vectors is one minus the cosine similarity.

In [ ]:
1 - np.dot(normalized_query, normalized_tc)  # cosine distance


0.29289321881345254

In [ ]:
1 - np.dot(normalized_query, normalized_wired)  # cosine distance

0.00410679353229626